### ISSUE TITLE
Mod infinitely skipping time when no players online

### ISSUE THREAD

**Issue by AntalaFilip** [FoxMcloud5655/RealisticSleep#1]
Hey. I'm running a forge 1.16.5 dedicated server with your mod, but there's a slight annoyance with it - **it logs a message into the console every tick**, making it very hard to see other things that are happening.
Looking through your code it seems like adding a toggle for the DEBUG final static boolean to the config would fix this.
Thanks!

**Comment by AntalaFilip** [comment]
Although after reading the code a bit more, it seems that the main problem is, if there are no players on a dedicated server, the mod infinitely tries to skip time due to the `areAllPlayersSleeping` property (realisticsleep.java 102) being set to true from start, and as there are no players, it doesn't switch over to false.
Adding a check if there are no players online should fix this problem.

**Comment by FoxMcloud5655** [comment]
I see.  I probably should check to see if dedicated servers run my mod properly before deploying it, shouldn't I?

I'll look through this tomorrow.

**Comment by FoxMcloud5655** [comment]
I just got around to fixing this...  Sorry for the wait.
