### ISSUE TITLE
 [1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [FoxMcloud5655/RealisticSleep#2]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for RealisticSleep-1.19-2.0.0.1-universal.

**Comment by FoxMcloud5655** [comment]
Interesting.  I will have to look into this, but I am unsure of what it could be, as I'm not exactly in the 1.19 development space right now.

It may be a while, but thank you for reporting this, and I will take a look at it.

**Comment by FoxMcloud5655** [comment]
Technically fixed, but not addressed as Forge version 41.1.0 is the latest version available now for 1.19.
