### ISSUE TITLE
Realistic Sleep fails to load correctly in 1.19 using Forge 41.1.0

### ISSUE THREAD

**Issue by GoldenDarius** [FoxMcloud5655/RealisticSleep#3]
After launching my modpack for some testing, Realistic Sleep failed to load along some other mods. Considering the error is _java.lang.reflect.InvocationTargetException: null_, I assume it has to be related to some changes in Forge's coding language.
Here's a crash report.
[crash-2022-08-21_12.38.34-fml.txt](https://github.com/FoxMcloud5655/RealisticSleep/files/9389148/crash-2022-08-21_12.38.34-fml.txt)

**Comment by FoxMcloud5655** [comment]
Realistic Sleep isn't the only one causing crashes here.  Spirit, Sapience, and Enchant With Mob are all causing your pack to crash too.  I'll fix what I can on my end if possible, but I do test my mods before I release them and it was working perfectly with this version of Forge the last time I checked.

**Comment by GoldenDarius** [comment]
Oh i have reported each mod crash to their github pages, and I managed to fix enchant with mob but had to remove spirit. I tested it again and Realistic Sleep is still causing the crash alongside sapience, however the crash for sapience seems to be of different nature than forge version

**Comment by FoxMcloud5655** [comment]
So apparently between Forge versions 41.0.x and 41.1.x, enough changes are present that it breaks mods.

You'll need to downgrade Forge or wait for the mods to be updated.

**Comment by GoldenDarius** [comment]
I see, well then. Thank you for clearing out
