### ISSUE TITLE
Not ticking during sleep

### ISSUE THREAD

**Issue by Testing123-svg** [FoxMcloud5655/RealisticSleep#4]
I keep getting errors and sleeping just does what vanilla sleeping does.

Attached is my latest log. Not sure what else you need.

Forge Version: 40.1.73
Mod Verison: RealisticSleep-1.18.2-2.0.0.1-universal.jar

[latest.log](https://github.com/FoxMcloud5655/RealisticSleep/files/9435224/latest.log)

**Comment by FoxMcloud5655** [comment]
Fixed in latest release to CurseForge.
