### ISSUE TITLE
Not working properly on 1.19

### ISSUE THREAD

**Issue by mrxantar** [FoxMcloud5655/RealisticSleep#5]
When i go to bed after a second or two time starts passing quickly as if the mod works but then vanilla sleep happens so day instantly starts as if its vanilla.

Forge 41.1.0

UPD: Also, i cant open a mod config for some reason

**Comment by FoxMcloud5655** [comment]
What version of Realistic Sleep are you running?

**Comment by mrxantar** [comment]
Latest one, 2.1.0.2

**Comment by FoxMcloud5655** [comment]
Then you've likely got a mod conflict somewhere.  Mind listing your mods here?  You can force the game to crash with the F3 combo and post a crash report or upload the modlist.html file if this is a published pack (or if you simply export it in CurseForge).

**Comment by mrxantar** [comment]
Yea, sure
[forge 1.19.zip](https://github.com/FoxMcloud5655/RealisticSleep/files/9439984/forge.1.19.zip)

**Comment by mrxantar** [comment]
Sorry, couldnt upload a html file here

**Comment by mrxantar** [comment]
Oh, and dont mind Somniac Awoken. I was testing will it work on 1.19

**Comment by mrxantar** [comment]
It's not a mod conflict, cuz i just checked it out. I installed only SleepWarp, and it still not working properly
