### ISSUE TITLE
The Night Not Ticking Away (1.16.5)

### ISSUE THREAD

**Issue by MianReplicate** [FoxMcloud5655/RealisticSleep#6]
MC Version: 1.16.5
Forge Version: 36.2.39
Mod Version: 1.3.5.64

Sleeping in a bed instantly skips the night like vanilla which I know is definitely not supposed to happen lol. Errors do pop up in the console though so maybe you can figure it out somehow.

When we sleep I get errors like these
![image](https://user-images.githubusercontent.com/60836125/205216192-1621c8d1-9769-4d46-b671-a93d02018bf0.png)

Log: 
[latest.log](https://github.com/FoxMcloud5655/RealisticSleep/files/10138137/latest.log)

**Comment by itsfolf** [comment]
+1 on 1.18.2

**Comment by FoxMcloud5655** [comment]
I thought I already fixed this?  Maybe I did and I never built it...

**Comment by itsfolf** [comment]
"Working version of method 3" and "Rework of method 3" were never ported to 1.18, could be related.

**Comment by FoxMcloud5655** [comment]
Fixed in latest release to CurseForge.
