### ISSUE TITLE
Unknown Issue: No mod mentioned

### ISSUE THREAD

**Issue by Steamroller99** [FoxMcloud5655/RealisticSleep#9]
[crash-2023-10-28_00.59.19-client.txt](https://github.com/FoxMcloud5655/RealisticSleep/files/13191540/crash-2023-10-28_00.59.19-client.txt)

Here's the crash report I have been searching for half a day now and I can't seem to find the problem of what's causing the crash. 

There's no mod mentioned, only a bunch of settings I have never seen. 

It might also be the forge launcher not really sure but the one I'm using now is the **43.3.2**

**Comment by FoxMcloud5655** [comment]
Your version of Iris is out of date.

**Comment by Steamroller99** [comment]
I don't use or have the mod iris....

**Comment by FoxMcloud5655** [comment]
Oculus is the Forge version of Iris, the mod the provides the ability to use shaders in Sodium.  Embeddium and Rubidium are ports of Sodium for Forge.

**Comment by Steamroller99** [comment]
So it's the shaders? Damn.... but my oculus is up to date same with rubidium, the problem might be on the rubidium side

**Comment by Steamroller99** [comment]
Welp anyways the problem's fix

**Comment by FoxMcloud5655** [comment]
I highly recommend using Embeddium instead, but good luck regardless.
